### ISSUE TITLE
Brush Editor - Raise an exception

### ISSUE THREAD

**Issue by Grum999** [Grum999/BuliBrushSwitch#19]
With v1.0.1, an exception is raised when trying to add/update a brush

Related to PkTk library update and `loadXmlUi`

**Comment by Grum999** [comment]
Normally fixed with v1.0.2 🤞

**Comment by cyanidearsenic** [comment]
I haven't been able to sit down and use it extensively, but I have it installed, and I can get into and edit the settings for brushes without issue now so hopefully that's the issue taken care of.

**Comment by Grum999** [comment]
Ok thanks!
At least the current bug seems to be fixed 🙂

There's no urgency, on my side I've not been able to sit down and draw something since April 😥


I'll close this issue, then if you see something else don't hesitate to open a new one!
